export const actionTypes = {

  // Base
  INIT_USER: 'INIT_USER',
  GET_USER: 'GET_USER',
  LOGOUT: 'LOGOUT',
  CHANGE_USER: 'CHANGE_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  // Anonymous
  LOGIN_USER: 'LOGIN_USER',

  // Admin
  GET_INITIAL_METER_DATA: 'GET_INITIAL_METER_DATA',
  GET_CORRECTED_METER_DATA: 'GET_CORRECTED_METER_DATA',
  CREATE_CORRECTED_METER_DATA: 'CREATE_CORRECTED_METER_DATA',
  DELETE_CORRECTED_METER_DATA: 'DELETE_CORRECTED_METER_DATA',
  GET_CORRECTED_DATA_BY_METER: 'GET_CORRECTED_DATA_BY_METER',

  // User
}

export const mutationTypes = {
  // Base
  SET_LOADER: 'SET_LOADER',
  SET_TOKEN: 'SET_TOKEN',
  SET_AUTH: 'SET_AUTH',
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',

  // Anonymous

  // Admin
  SET_INITIAL_METER_DATA: 'SET_INITIAL_METER_DATA',
  SET_INITIAL_METER_DATA_PAGE: 'SET_INITIAL_METER_DATA_PAGE',
  SET_INITIAL_METER_DATA_PAGES_COUNT: 'SET_INITIAL_METER_DATA_PAGES_COUNT',
  SET_INITIAL_METER_DATA_FILTERS: 'SET_INITIAL_METER_DATA_FILTERS',
  SET_CORRECTED_METER_DATA: 'SET_CORRECTED_METER_DATA',
  UPDATE_CORRECTED_METER_DATA: 'UPDATE_CORRECTED_METER_DATA',
  APPEND_CORRECTED_METER_DATA: 'APPEND_CORRECTED_METER_DATA',
  REMOVE_CORRECTED_DATA_BY_METER: 'REMOVE_CORRECTED_DATA_BY_METER',
  SET_CORRECTED_DATA_BY_METER: 'SET_CORRECTED_DATA_BY_METER',

  // User

  // User and admin
}
